[package]
name = "dht"
version = "0.1.0"
authors = ["bene"]
edition = "2018"

[dependencies]
bigint = { version = "4.4.1", features = ["std"] }
byteorder = "1.3.2"
log = "0.4.8"
sha2 = "0.8.0"
rust-ini = "0.13.0"
stderrlog = "0.4.1"
structopt = "0.3.2"
threadpool = "1.7.1"
lazy_static = "1.4.0"
